      - name: Install Argo CD
        run: |
          kubectl create namespace argocd || true
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          kubectl -n argocd rollout status deploy/argocd-server --timeout=180s
          kubectl -n argocd rollout status deploy/argocd-repo-server --timeout=180s
